model:
  hidden_size: 512
  num_pts: 128
  num_dims: 2
  learning_rate: 0.001
  save_name: "ectencoder_mnist_rotated.ckpt" 

layer: 
  ect_size: 64
  dim: 2

data: 
  module: datasets.mnist_rotated
  root: "./data/mnistpointcloud"
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False


trainer:
  accelerator: auto
  max_epochs: 100
  log_every_n_steps: 1


loggers: 
  project: toporecon-dev
  entity: aidos-labs
  save_dir: ./lightning_logs
